server:
  port: 8783
spring:
  application:
    name: service-hi-ha
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:8001/eureka/,http://peer3:8002/eureka/,http://peer1:8000/eureka/
    fetch-registry: false
    register-with-eureka: false