spring:
  profiles:
    active:
      - dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: config-server
eureka:
  client:
    service-url:
      defaultZone: http://peer2:8001/eureka/,http://peer3:8002/eureka/,http://peer1:8000/eureka/
---
server:
  port: 8001
spring:
  profiles: test
  application:
    name: config-server
eureka:
  client:
    service-url:
      defaultZone: http://peer2:8001/eureka/,http://peer3:8002/eureka/,http://peer1:8000/eureka/
